[[headers]]
for = "/postCatView/* /postCatView/:splat 302!"
[headers.values]
[[headers]]
for = "/postView/* /postView/:splat 302!"
[headers.values]
[[headers]]
for = "/postFront/* /postFront/:splat 302!"
[headers.values]
[[headers]]
for = "/ index.html 200"
[headers.values]